
[all:vars]
ansible_connection=ssh
ansible_user=bigboss

[foreman_katello]
# Your remote target node
foreman-01.dmostlab.com ansible_host=10.0.20.30

[gitlab_main]
gitlab-01.dmostlab.com ansible_host=10.0.20.40


[wazuh_aio]
wazuh-01.dmostlab.com ansible_host=10.0.20.50
